[package]
name = "bevy_tasks"
version = "0.9.0-dev"
edition = "2021"
description = "A task executor for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
async-io = ["async-global-executor/async-io"]
tokio = ["async-global-executor/tokio"]

[dependencies]
futures-lite = "1.4.0"
async-global-executor= { version="2.0.2", default-features = false }
futures-lite = "1.12.0"
event-listener = "2.4.0"
async-executor = "1.3.0"
async-channel = "1.4.2"
once_cell = "1.7"
concurrent-queue = "1.2.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"

[dev-dependencies]
instant = { version = "0.1", features = ["wasm-bindgen"] }
