[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    "RUSTSEC-2020-0056", # from gilrs v0.8.1 - unmaintained - https://github.com/koute/stdweb/issues/403
    "RUSTSEC-2021-0139" # from ansi_term v0.12.1 - unmaintained - https://github.com/ogham/rust-ansi-term/issues/72
]

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow = [
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "0BSD",
    "BSD-2-Clause",
    "CC0-1.0",
]
exceptions = [
    { name = "unicode-ident", allow = ["Unicode-DFS-2016"] },
]
default = "deny"

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
    { name = "ahash", version = "0.4" },
    { name = "android_log-sys", version = "0.1" },
    { name = "cfg-if", version = "0.1" },             # https://github.com/rustwasm/console_error_panic_hook/pull/18
    { name = "core-foundation", version = "0.6" },
    { name = "core-foundation", version = "0.7" },
    { name = "core-foundation-sys", version = "0.6" },
    { name = "core-foundation-sys", version = "0.7" },
    { name = "core-graphics", version = "0.19" },
    { name = "fixedbitset", version = "0.2" },
    { name = "hashbrown", version = "0.9" },
    { name = "jni", version = "0.18.0" },
    { name = "jni", version = "0.19.0" },
    { name = "libm", version = "0.1" },
    { name = "mach", version = "0.2" },
    { name = "ndk", version = "0.2" },
    { name = "ndk-glue", version = "0.2" },
    { name = "num_enum", version = "0.4" },
    { name = "num_enum_derive", version = "0.4" },
    { name = "proc-macro-crate", version = "0.1" },
    { name = "stdweb", version = "0.1" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
